//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptagricDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CropField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CropField()
        {
            this.Images = new HashSet<Images>();
            this.Inter_Water_Reource = new HashSet<Inter_Water_Reource>();
            this.SubRegion = new HashSet<SubRegion>();
        }
    
        public int ID { get; set; }
        public Nullable<System.Guid> CustomerID { get; set; }
        public int LocationID { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inter_Water_Reource> Inter_Water_Reource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubRegion> SubRegion { get; set; }
        public virtual Location Location { get; set; }
    }
}
