//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptagricDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int ID { get; set; }
        public string SmallURL { get; set; }
        public string MiddleURL { get; set; }
        public string BigURL { get; set; }
        public string Type { get; set; }
        public Nullable<int> CF_TypeValueID { get; set; }
        public Nullable<int> SR_TypeValueID { get; set; }
        public Nullable<System.DateTime> ImageDate { get; set; }
    
        public virtual CropField CropField { get; set; }
        public virtual SubRegion SubRegion { get; set; }
    }
}
