//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptagricDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inter_Water_Reource
    {
        public int WR_ID { get; set; }
        public int CF_ID { get; set; }
        public int SourcePriority { get; set; }
    
        public virtual CropField CropField { get; set; }
        public virtual WaterResource WaterResource { get; set; }
    }
}
