//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptagricDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubRegion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubRegion()
        {
            this.Images = new HashSet<Images>();
            this.Predictions = new HashSet<Predictions>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public int CF_ID { get; set; }
        public int CropTypeID { get; set; }
        public Nullable<int> CroppedProductAmount { get; set; }
        public Nullable<int> SoilWaterContent { get; set; }
        public Nullable<int> CalculatedCropProduction { get; set; }
        public Nullable<int> CalculatedWaterConsumption { get; set; }
        public Nullable<int> CalculatedDisasterAmount { get; set; }
        public Nullable<System.DateTime> CalculationDate { get; set; }
    
        public virtual CropField CropField { get; set; }
        public virtual CropType CropType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Predictions> Predictions { get; set; }
    }
}
